version: '3.8'

services:
  mongo:
    image: mongo
    container_name: engweb2025-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  web:
    build: .
    container_name: engweb2025-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MONGO_URL=mongodb://mongo:27017/engweb2025
    command: npm run dev

volumes:
  mongo-data:
